/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { NotificationType } from "./NotificationType";
import { NotificationTypeCountArgs } from "./NotificationTypeCountArgs";
import { NotificationTypeFindManyArgs } from "./NotificationTypeFindManyArgs";
import { NotificationTypeFindUniqueArgs } from "./NotificationTypeFindUniqueArgs";
import { DeleteNotificationTypeArgs } from "./DeleteNotificationTypeArgs";
import { NotificationTypeService } from "../notificationType.service";
@graphql.Resolver(() => NotificationType)
export class NotificationTypeResolverBase {
  constructor(protected readonly service: NotificationTypeService) {}

  async _notificationTypesMeta(
    @graphql.Args() args: NotificationTypeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [NotificationType])
  async notificationTypes(
    @graphql.Args() args: NotificationTypeFindManyArgs
  ): Promise<NotificationType[]> {
    return this.service.notificationTypes(args);
  }

  @graphql.Query(() => NotificationType, { nullable: true })
  async notificationType(
    @graphql.Args() args: NotificationTypeFindUniqueArgs
  ): Promise<NotificationType | null> {
    const result = await this.service.notificationType(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => NotificationType)
  async deleteNotificationType(
    @graphql.Args() args: DeleteNotificationTypeArgs
  ): Promise<NotificationType | null> {
    try {
      return await this.service.deleteNotificationType(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
